//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEasy.Data
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;
    using System.Windows.Media;

    public partial class FEECHKI_VINKS
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public string Vendor { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<float> Count { get; set; }
        public Nullable<int> Discount { get; set; }

        public SolidColorBrush solidColorBrush
        {
            get
            {
                if(this.Discount > 15)
                {
                    SolidColorBrush brush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#7fff00"));
                    return brush;
                }
                else
                {
                    return Brushes.Transparent;
                }
            }
        }
        public string ImgPath
        {
            get
            {
                return "/Resources/ProductImg/" + this.FullName + ".png";
            }
        }
        public string FullNameText
        {
            get
            {
                return "Наименование:\n"+this.FullName;
            }
        }
        public string DescriptionText
        {
            get
            {
                return "Описание:\n" + this.Description;
            }
        }
        public string VendorText
        {
            get
            {
                return "Производитель:\n" + this.Vendor;
            }
        }
        public string PriceText
        {
            get
            {
                if(this.Discount > 0)
                {
                    string str = this.Price.ToString();
                    float? newPrice = this.Price - (this.Price * this.Discount / 100);
                    string through = "";
                    foreach (char c in str)
                    {
                        through += c + "\u0336";
                    }
                    return "Старая цена:\n" + through + "\nЦена:\n" + newPrice + "р.";
                }
                else
                {
                    return "Цена:\n" + this.Price + "р.";
                }
            }
        }
        public string DiscountText
        {
            get
            {
                return "Скидка:\n" + this.Discount + "%";
            }
        }
    }
}
