//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalPointCPKiOv2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOfService
    {
        public int Key { get; set; }
        public int IDOrders { get; set; }
        public int IDService { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
