//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDecor.Data
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class ProductTable
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public int Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }

        public SolidColorBrush solidColorBrush
        {
            get
            {
                if(this.Discount >= 4)
                {
                    SolidColorBrush brush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#7fff00"));
                    return brush;
                }
                else
                {
                    return Brushes.Transparent;
                }
            }
        }

        public string imgPath
        {
            get
            {
                return "/Resources/ProductsDecor/" + this.Image;
            }
        }

        public String category
        {
            get { return "Категория:\n" + this.Category; }
        }

        public String description
        {
            get { return "Описание:\n" + this.Description; }
        }

        public String price
        {
            get
            {
                if(this.Discount > 0 && this.Discount != null)
                {
                    string str = this.Price.ToString();
                    double? newPrice = this.Price - (this.Price * this.Discount / 100);

                    string through = "";

                    foreach(char c in str)
                    {
                        through += c + "\u0336";
                    }

                    return "Старая цена\n" + through + "\nНовая цена\n" + newPrice;
                }
                else
                {
                    return "Цена\n" + this.Price;
                }
            }
        }

        public String discount
        {
            get
            {
                if(this.Discount == null || this.Discount < 0)
                {
                    return "Действующая скидка\n --";
                }
                else
                {
                    return "Действующая скидка\n" + this.Discount + "%";
                }
            }
        }

        public String quantity
        {
            get
            {
                if (this.Quantity == null)
                {
                    return "Кол-во на складе\n --";
                }
                else
                {
                    return "Кол-во на складе\n" + this.Quantity + "шт.";
                }
            }
        }
    }
}
